### ISSUE TITLE
Charts components

### ISSUE THREAD

**Issue by stanleygomes** [marco-tulio-melo/marvue#5]
Maybe use Apex charts for vue:
https://apexcharts.com/docs/vue-charts/

**Comment by GermanoRenner** [comment]
I like ApexCharts but, i taked a look in vue-google-charts, it's can be interesting use too.
https://github.com/devstark-com/vue-google-charts?ref=madewithvuejs.com

**Comment by marco-tulio-melo** [comment]
feature/marcotuliomelo_#27
